postgres:
  image: postgres:9.4
  volumes:
    - /data/django_bootstrap/postgres:/var/lib/postgresql/data
  env_file: .env

django:
  build: .
  user: django
  links:
    - postgres
    - redis
  command: /gunicorn.sh
  env_file: .env

nginx:
  build: ./compose/nginx
  links:
    - django
  ports:
    - "0.0.0.0:80:80"

redis:
  image: redis:3.0
